# -*- coding: utf-8 -*-
""".ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1misgDppbhYM-mgC8dC9zuRdVrbyk7DAB
"""

print("hello")

print ("hello tom \n")

print("hello \n world")

#multi string is given by '''
address=''' jjkj
jjjjngj'''
print (address)

#slicing
state = "rajasthan"
state [-3]

#slicing operator
state="rajasthan"
print (state[0:3])
print(state [-3])
print(state[2:6])
print(state[3:5])
print(state[3:8])
print(state[3:10:5])
print(state[0:10:2])
#negative indexing
#print(state[-1:3])
print(state[-2:-5:-1])
print(state[:5])

#list -datatype store multiple value / storing any type of value
# list is mutable
mylist=[4,6,7,4,44,"hello","Dean"]
print(mylist)
print (mylist[:1])
print (mylist[0:5])
print (mylist[3:8])
mylist.append(77)
print (mylist)
'''extend--'''
mylist.extend("hello")
print (mylist)
#add at index
mylist[0]=100
print (mylist)
#to pop the value
print(mylist.pop(5))
#to delete
#print(mylist.remove("hello"))

#tuple
# # bracket is optional
mytuple=(27,34,56)
print(type(mytuple))
mytuple[2]

#dictionary
#key: value format
#mutable
mydictionary={101:45,102:45}
print(mydictionary)
#print (mydictionary[100]="hi")
#to delete
'''mydictionary.pop("rollno")
x=mydictionary.pop(1)
print(x)'''
#------------------------
#dictionary has unique key and values
#key will be always imuatble but not be list
#----------------------------
#mydictionary.key()
#mydictionary.values()

#set datatype ,unique value ,
myset={29,45,45,6787}
print(myset)
myset.remove(45)
print (myset)
myset.discard(23) # discard method never gives error
print(myset)
#union
myset1={10 ,20,30,40}
myset2={50,60,70}
myset1.union(myset2)
myset1.intersection(myset2)

#pandas -inbuild library data cleansing,manipulate,process of data
import pandas
#series and data frame

pandas.Series(["sd","fg"])
#string datatype =object
pandas.Series([34,456,67])

import pandas as pd
#any name can be given to pandas here"pd" knows as alias (nickname)

pd.Series([23,45,67,788])

pd.Series({"E":34,
           "t":54})

seriesdata=pd.Series({"product A":100,
                     "product b" :45,
                      "product c":300})

#index checking
seriesdata.index

# lenght =total no of series
len(seriesData)

dict(seriesData)

#seriesdata.indexmin()

seriesData.idxmax()

seriesdata["Product A"]=99

seriesData.sort_values(ascending=False)

#creating dataframe
numberseries=pd.Series([20,30,40])
nameseries=pd.Series(["tom","jerry","spike"])

pd.DataFrame([numberseries,nameseries])

pd.DataFrame({"name":numberseries,"number":nameseries})

from google.colab import files
uploaded=files.upload()

import pandas as pd
import io
df = pd.read_csv(io.BytesIO(uploaded['NbaInfo.csv']))
print(df)

df.drop(2)

df = pd.read_csv(io.BytesIO(uploaded['NbaInfo.csv']))
df.info()

df.fillna("unkown")

df=["Salary"]=df("unknown")

df["Salary"]=df["Salary"].fillna(0)

df["Salary"]=df["Salary"]
df.head(0)

#dropping nsa ,filling nsa , creating new

df["Salary"]

#dataype change
#number store =float type
#first fill
df["Salary"].astype(int)

df["Weight"]

df["Weight"]=df["Weight"].fillna(0)
#fill nan value of weight and change the datatype to int

df["Weight"]

df["Salary"].astype(int)

df["Position"].unique()

#remove nan value
df=df.dropna()
df["Position"].unique()

df["Position"]

#printing unique
df["Position"]=df["Position"].astype("category")
df.info()

df["Team"]

#df["Category"]=df["Category"].fillna(0)

#operation in position

df["Age"]

[df["Age"]>25.0]

df["Weight"]

#[df["Age"]>25.0 && ["Wreight"]>200]

count1=df["Age"]>25.0
count2=df["Weight"]>200.0
df[(df["Age"]>25.0) &(df["Weight"]>200.0)]

#download youtube video
#py qr code qr code genrating
#send whatsapp text

